# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space # or 'tab'
        width: 4

    NestingDepth:
        enabled: true
        max_depth: 4
        ignore_parent_selectors: false

    PropertySortOrder:
        enabled: false
        ignore_unspecified: false
        min_properties: 2
        separate_groups: false
