language: node_js
node_js:
  - "8"
  - "7"
  - "6"

cache:
  yarn: true

before_script:
  - yarn install
script:
  - yarn run gulp html
  - yarn run gulp css
  - yarn run zip
  - yarn run clear
  - yarn run build
