language: node_js
node_js:
  - "8"
  - "7"
  - "6"

cache:
  yarn: true

before_script:
  - yarn install
script:
  - yarn run gulp html
  - yarn run gulp css
  - yarn run gulp scripts
  - yarn run gulp assets
  - yarn run build
